### ISSUE TITLE
Typecast error in build_config when using dart2

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/build#1293]
Attempting to run the angular compiler using --preview-dart-2 and getting a runtime cast failure in build_config:

```
Unhandled exception:
type 'YamlMap' is not a subtype of type 'Map<String, dynamic>' in type cast where
  YamlMap is from package:yaml/src/yaml_node.dart
  Map is from dart:core
  String is from dart:core

#0      Object._as (dart:core/runtime/libobject_patch.dart:67:25)
#1      parseFromYaml (package:build_config/src/parse.dart:78:30)
#2      new BuildConfig.parse (package:build_config/src/build_config.dart:113:7)
#3      BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart:72:18)
<asynchronous suspension>
#4      _packageBuildConfig (package:build_runner/src/package_graph/target_graph.dart:55:22)
<asynchronous suspension>
#5      TargetGraph.forPackageGraph (package:build_runner/src/package_graph/target_graph.dart:29:17)
<asynchronous suspension>
#6      build (package:build_runner/src/generate/build_impl.dart:73:41)
<asynchronous suspension>
#7      build (package:build_runner/src/generate/build.dart:69:16)
#8      _BuildCommand.run (package:build_runner/src/entrypoint/options.dart:319:24)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#11     new Future.sync (dart:async/future.dart:224:31)
#12     CommandRunner.run (package:args/command_runner.dart:109:11)
#13     run (package:build_runner/src/entrypoint/run.dart:22:31)
<asynchronous suspension>
#14     main (file:///Users/alorenzen/angular/examples/registration_form/.dart_tool/build/entrypoint/build.dart:63:26)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:275:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by jakemac53** [comment]
We can/will fix this for sure, but just fyi you are probably going to get a lot of errors here from other packages (analyzer, etc).

**Comment by alorenzen** [comment]
Yup, just trying to knock them down one by one. Since they're all runtime failures, it's hard to see what's broken in Angular before the others are fixed.

**Comment by jakemac53** [comment]
Hmm, looks like we have to turn the YamlMap into a regular Map, its keys are actually `YamlNode` but are typed dynamic because they allow lookup by string.

**Comment by jakemac53** [comment]
@alorenzen what did you actually run to get this particular error? I am sure there are more across all the other build packages as well....

**Comment by jakemac53** [comment]
(If I run a normal build script with --preview-dart-2 I get a fasta error)

**Comment by natebosch** [comment]
I can reproduce this with:

```sh
cd e2e_example
dart --preview-dart-2 ../build_runner/bin/build_runner.dart build
```

fasta errors are tracked in https://github.com/dart-lang/sdk/issues/31623

**Comment by alorenzen** [comment]
Oh, right. I had a local fix for that.

**Comment by alorenzen** [comment]
https://github.com/dart-lang/angular/pull/1241

**Comment by alorenzen** [comment]
```
cd examples/registration_form
dart --preview-dart-2 .dart_tool/build/entrypoint/build.dart build
```

**Comment by kevmoo** [comment]
json_serializable 0.5.4 is out!

**Comment by jakemac53** [comment]
Ok, I can go ahead and take on moving this to json_serializable

**Comment by kevmoo** [comment]
Good luck!

**Comment by natebosch** [comment]
Fixed by #1486

**Comment by maxwellpeterson-wf** [comment]
I'm still seeing this error while trying to write a new BuildRunner in Dart 2:

```bash
» pub run build_runner build
[INFO] Generating build script completed, took 524ms
[SEVERE] wdesk_sdk|phase_one_builder:

type 'YamlMap' is not a subtype of type 'Map<dynamic, YamlNode>'
[SEVERE] wdesk_sdk|phase_one_builder:
Failed to instantiate builder for wdesk_examples with configuration:
{}
```

The `build.yaml` looks like this so far:

```yaml
builders:
  phase_one_builder:
    import: "package:wdesk_sdk/phase_one_builder.dart"
    builder_factories: ["phaseOneBuilder"]
    build_extensions: {"$web$": ["index.html", "prod/index.html"]}
    auto_apply: dependents
```

It seems to be a type issue when parsing `{"$web$": ["index.html", "prod/index.html"]}`

Any help is greatly appreciated!

**Comment by natebosch** [comment]
looks like you have a cast in your `wdesk_sdk|phase_one_builder` factory, all of the casts should be resolved in the `build_config` code...

Can you run with `--verbose` to get a full stack trace so we can confirm?

**Comment by maxwellpeterson-wf** [comment]
Thanks @natebosch, running it with `--verbose` pointed me to the issue, which was occurring in the initializer of my builder. All good now 🙂
