### ISSUE TITLE
Can't deploy AngularDart app to firebase: Error: ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#1751]
## Environment

* Dart: Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
* Packages:
```
  angular 5.0.0
  angular_forms 2.0.0
  angular_router 2.0.0-alpha+19
  angular_test 2.0.0
  build 0.12.7+3
  build_runner 0.10.1
  build_test 0.10.3+1
  build_web_compilers 0.4.2+1
```

## Steps to reproduce

0. `npm install -g firebase-tools`.
    You'll also need to have access to a **firebase project as a target for deployment**.
1. Download https://github.com/angular-examples/toh-5
2. `pub upgrade`
3. `webdev build --output build`
4. `firebase init`. Configure for hosting.
5. In the `firebase.json` file set the `hosting.public` field to `"build/web"`.
6. `firebase use <your-project>`
7. `firebase serve` and launch the app in a browser. It should run fine.
8. `firebase deploy --debug` results in

```console
> firebase deploy --debug
...
=== Deploying to 'angulardart-org-dev3'...

i  deploying hosting
i  hosting: preparing build/web directory for upload...
[2018-08-11T18:45:16.705Z] Error: ELOOP: too many symbolic links encountered, stat '/Users/chalin/git/dart/site-webdev/examples/ng/doc/toh-5/build/web/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages/packages'
```

This seems to be because `build/packages` contains a link to itself

    packages -> ../packages

If I delete this symlink, the app still serves ok locally, and deployment succeeds. The deployed app works as well.

cc @kwalrath @kevmoo 

This issue is from this [SO Question](https://stackoverflow.com/questions/51800724/firebase-and-angulardart-error-there-was-an-issue-preparing-hosting-files-for).

**Comment by chalin** [comment]
Hmm, there have been some important firebase changes recently, so maybe this is new firebase behavior. Is the `build/packages/packages` really needed? We had symlink issues not to long ago, but I thought that they had been resolved.

**Comment by jakemac53** [comment]
The issue around packages symlinks in the packages dir should be fixed now, see https://github.com/dart-lang/build/issues/1723.

Can you update to the latest build_runner_core and confirm its fixed?

**Comment by jakemac53** [comment]
It is definitely expected that `build/web/packages` is a symlink to `build/packages`. We don't want to copy all the files there and it must exist so that files can be properly loaded.

What should not exist any longer, and sounded like the root cause of this problem, is the `build/packages/packages` symlink to itself, which created an infinite loop of symlinks.

**Comment by chalin** [comment]
No, the cause was the symlink under web (`firebase deploy` still fails). From the message in the opening comment:

> Error: ELOOP: too many symbolic links encountered, stat '/Users/chalin/git/dart/site-webdev/examples/ng/doc/toh-5/_**build/web/packages**_/packages/packages/...'

**Comment by jakemac53** [comment]
Note the nested `packages` directories though, it looks like you are still getting an infinite loop of packages dirs (and still have a `packages` symlink under your top level `packages` dir).

Can you try manually deleting your `build` directory and rebuilding? I think maybe we just didn't clean up that symlink, so it still exists from previous builds.

**Comment by chalin** [comment]
Here is what I've done, and notice that the symlink is still there:

```console
> pub upgrade
Resolving dependencies... (6.6s)
  ...
 > build_resolvers 0.2.2+1 (was 0.2.1+1)
  build_runner 0.10.1
 > build_runner_core 0.3.1+2 (was 0.3.1)
  build_test 0.10.3+1
 > build_web_compilers 0.4.2+1 (was 0.4.1)
  ...
Changed 5 dependencies!
...
> rm -Rf .dart_tool/ build
> webdev build -o build
[INFO] Building new asset graph completed, took 998ms
...
[INFO] Succeeded after 21.7s with 1980 outputs (5902 actions)
> ls -l build/packages/packages
lrwxrwxr-x  1 chalin  staff  11 Aug 13 12:51 build/packages/packages -> ../packages
```

**Comment by jakemac53** [comment]
Oh... it looks like this made it into 0.3.1+1 but not 0.3.1+2? We had a bit of a versioning snafu and it looks like the updated version did not get this fix.

cc @natebosch

**Comment by natebosch** [comment]
ugh, yeah I think I cherry picked one bug fix but not the one for this issue...

**Comment by chalin** [comment]
Could you also publish a version of `build_runner` that uses `build_runner_core` 0.3.1+3 as a min version? It will be easier to guide folks that way (since most projects don't depend on `build_runner_core` directly).

**Comment by natebosch** [comment]
A `pub upgrade` should get you that version

**Comment by chalin** [comment]
Yes it does. Ok, if that's the route we want to go.

**Comment by natebosch** [comment]
> Ok, if that's the route we want to go.

Yeah I think so - even if we publish another `build_runner` we'd either need to `pub upgrade` to get the latest version of that, or specify a `+x` release for our dep on `build_runner` which would be unusual.

**Comment by chalin** [comment]
SGTM

**Comment by chalin** [comment]
I'm still getting this issue with `build_runner_core 0.3.1+4`:

> **Error:  Too many levels of symbolic links** /Users/chalin/git/dart/sitewebdev/src/_data/code/examples/packages/packages/packages/...

**Comment by natebosch** [comment]
@chalin - are you getting the problem on a fresh output directory or when reusing an old one that previously had this issue? It's likely that once an output directory gets this problem it won't be cleaned up on subsequent builds and you'll need to remove the directory manually.

**Comment by chalin** [comment]
Yes, I was deleting the output directory, but I hadn't deleted the `.dart_tool` folder. Removing them both did the trick.

**Comment by natebosch** [comment]
Interesting... I would not have expected anything in `.dart_tool` to cause it to retain broken behavior... I guess if it's working going forward though it's not worth too much time sunk into to debugging further.

**Comment by chalin** [comment]
> ... if it's working going forward though it's not worth too much time sunk into to debugging further.

Agreed.
