### ISSUE TITLE
Test command not producing source maps correctly on build_web_compilers 2.0.0

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2264]
* Dart SDK Version: 2.3.0
* Relevant packages:
  * build 1.1.4
  * build_runner 1.4.0
  * build_runner_core 3.0.5
  * build_test 0.10.7+3
  * build_web_compilers 2.0.0
  * test 1.6.3
* What builder(s) you are using (or writing yourself): none, no custom `build.yaml`
* OS: MacOSX 10.14.4
* Browser: Chrome 74

----

With build_web_compilers 1.2.1 (the latest 1.x version), source maps work out of the box when running tests in the default debug mode. With a simple test file, running the following allows me to open chrome and set breakpoints in the source .dart files:

```
pub run build_runner test -- -p chrome --pause-after-load
```

After upgrading to build_web_compilers to 2.0.0, this functionality no longer works. The source .dart files still seem to be recognized (they are autocompleted when using cmd+p in the "Sources" tab of chrome dev tools), but their contents are completely empty.

If it helps, these are the transitive dependency changes that occur when upgrading from build_web_compilers 1.2.1 to 2.0.0:

```
> analyzer 0.36.3 (was 0.35.4)
> build_config 0.4.0 (was 0.3.2)
> build_daemon 0.6.0 (was 0.5.0)
> build_modules 2.1.2 (was 1.0.10)
> build_runner 1.4.0 (was 1.3.3)
> build_runner_core 3.0.5 (was 3.0.3)
> build_web_compilers 2.0.0 (was 1.2.1)
> dart_style 1.2.7 (was 1.2.4)
> front_end 0.1.18 (was 0.1.14)
> kernel 0.3.18 (was 0.3.14)
```

The `serve` task is unaffected by this upgrade. Source maps work before and after upgrading to build_web_compilers 2.0.0 when running:

```
pub run build_runner serve web
```

**Comment by jakemac53** [comment]
I think this is an issue with the source map uris being absolute paths - the test runner serves tests under a separate directory so only a relative path will really work in that context.

We are revisiting all of our uris (its way more complicated than you would believe :D), so I will make sure we consider this issue as a part of that. It is going to be important for more than just tests too, basically the current sourcemaps will only work when the root of the server is a top level directory in the package (like `test` or `web`).

**Comment by jakemac53** [comment]
cc @Markzipan this is also relevant for what you are looking into :).

The general solution we are moving towards here is to use relative paths wherever possible. That should fix this issue as well as other related issues by making the source maps more portable (they won't have any assumption about what the server root is any more).

**Comment by jakemac53** [comment]
@evanweible-wf can you confirm this is resolved if you update to 2.4.0-dev.0.0 and the latest build_web_compilers?

**Comment by evanweible-wf** [comment]
@jakemac53 Yup, looks to be working on 2.4.0-dev.0.0 + build_web_compilers 2.1.1!

**Comment by evanweible-wf** [comment]
@jakemac53 sorry, I misremembered the original issue. Sourcemaps work via `webdev serve` but if I run `pub run build_runner test -- -p chrome --pause-after-load`, I still see blank files when opening up `.dart` assets in the sources pane.

**Comment by jakemac53** [comment]
Whoops, I thought that the change landed in the last sdk release but it looks like I was wrong. Things should be working at head though (or in the next dev release). Will wait to close until I get confirmation.

**Comment by evanweible-wf** [comment]
@jakemac53 this is working now on 2.5.0-dev.0.0 👍

**Comment by jakemac53** [comment]
:tada:
