### ISSUE TITLE
Not exiting after build finishes

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#836]
Something in the dart_web_compilers package is holding the VM open. I can see that the processes for analyzer and dartdevc are exiting, but we seem to still hold some isolate ports open to listen to them.

In the observatory UI I can see some `_NativeSocket` instances related to these processes.

We've seen this type of problem before...

**Comment by jakemac53** [comment]
Is this just with the switch to isolates? I was doing some normal builds today that exited as expected

**Comment by natebosch** [comment]
No, I am seeing the same thing on `master`.

**Comment by jakemac53** [comment]
Is this fixed now as well?

**Comment by natebosch** [comment]
This is not fixed. Same repro instructions still apply on master branch.

**Comment by natebosch** [comment]
Ugh, I don't know how but I was getting an old version of `bazel_worker` and just seeing https://github.com/dart-lang/build/issues/655 all over again.

`pub upgrade` fixed this.
